--2513310025 âªµÔÃÑµ¹ì »Ñ´ªÒ

--1
SELECT DEPARTMENT_ID,concat(concat(DEPARTMENT_NAME,' '),LOCATION_ID) as "INFO"
FROM DEPARTMENTS
WHERE DEPARTMENT_ID >= '&dept'
ORDER BY &dept ;

--2
SELECT JOB_ID,JOB_TITLE ,&col
FROM JOBS
WHERE JOB_ID='&job';
--3
SELECT COUNTRY_NAME
FROM COUNTRIES
where COUNTRY_NAME LIKE'__i%';
--4
SELECT concat(concat (FIRST_NAME,' '),LAST_NAME) as EMP_NAME ,SALARY,COMMISSION_PCT
FROM EMPLOYEES
where FIRST_NAME LIKE'e'and SALARY in (2.0,0.4) 
ORDER BY COMMISSION_PCT;
